[package]
name = "nois"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.7.0"
pest = "2.5.1"
pest_derive = "2.5.1"
colored = "2.0.0"
enquote = "1.1.0"
clap = { version = "3.2.23", features = ["derive"] }
